boatd:
    port: 2222
    interface: 0.0.0.0

plugin_directory: null

plugins:
    - mavlink:
        enabled: true
        device: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AD01UBXA-if00-port0'
        baud: 115200

driver:
    #file: ~/git/sails-boatd-driver/driver.py
    module: dewi_boatd_driver


behaviours:
    - station-keeping:
        file: station-keeping-behaviour
    - idle:
        file: idle-behaviour
