---
- hosts: all
  gather_facts: true
  sudo: yes
  tasks:
    - name: update apt cache
      command: apt-get update

    - name: install ansible prerequisites
      command: apt-get install -y python python-apt python-pycurl sshpass

    - name: install base requirements
      apt: name={{ item }} state=present
      with_items:
          - gpsd
